name: Build and Release WPF App
on:
  push:
    # Exclude non-version tag pushes
    tags:
      - 'v*.*.*'

env:
    SOLUTION_PATH: "src/MaraudersModManager/MaraudersModManager.sln"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet Packages
      run: dotnet restore MaraudersModManager.sln

    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} -c Release

    - name: Publish
      run: dotnet publish ${{env.SOLUTION_PATH}} -c Release -r win-x64 /p:PublishSingleFile=true /p:PublishTrimmed=true
      env:
        PUBLISH_DIR: ./bin/Release/net6.0-windows/win-x64/publish

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Artifacts
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.PUBLISH_DIR }}/*
        asset_name: WPFApp.zip
        asset_content_type: application/zip